export default {
  userQuizzes: 'userQuizzes',
  searchUsers: 'searchUsers',
  searchQuizzes: 'searchQuizzes',
  friendRequests: 'friendRequests',
  QuizAnswers: 'QuizAnswers',
  EditProfile: 'EditProfile',
  UserProfile: 'UserProfile',
  ContactUs: 'ContactUs',
  ChangeTheme: 'ChangeTheme',
  ChangeLanguage: 'ChangeLanguage',
  AddQuestions: 'AddQuestions',
  ConfirmCode: 'ConfirmCode',
  ResetPassword: 'ResetPassword',
  ForgotPassword: 'ForgotPassword',
  Register: 'Register',
  QuizDetails: 'QuizDetails',
  QuizIntro: 'QuizIntro',
  CategoryDetails: 'CategoryDetails',
  JoinQuiz: 'JoinQuiz',
  CreateQuiz: 'CreateQuiz',
  Tabs: 'Tabs',
  Login: 'Login',
  OTP: 'OTP',
  Landing: 'Landing',
  UserFriends: 'UserFriends',
};
